In [1]:
#Web scraping assignment-4
#Name-Vipul Anand
#Batch=DS2312

In [1]:
import selenium
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
from selenium.webdriver.chrome.options import Options
import regex as re

In [3]:
#Question-1

In [14]:
driver=webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [23]:
Name=[]
Artist=[]
Upload_date=[]
Views=[]

In [15]:
name=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[1]')

In [24]:
for i in name:
    a=i.text
    Name.append(a.split('[')[0])
print(Name,len(Name))

['"Baby Shark Dance"', '"Despacito"', '"Johny Johny Yes Papa"', '"Bath Song"', '"Shape of You"', '"See You Again"', '"Wheels on the Bus"', '"Phonics Song with Two Words"', '"Uptown Funk"', '"Learning Colors – Colorful Eggs on a Farm"', '"Gangnam Style"', '"Masha and the Bear – Recipe for Disaster"', '"Dame Tu Cosita"', '"Axel F"', '"Sugar"', '"Counting Stars"', '"Baa Baa Black Sheep"', '"Roar"', '"Lakdi Ki Kathi"', '"Waka Waka (This Time for Africa)"', '"Sorry"', '"Thinking Out Loud"', '"Humpty the train on a fruits ride"', '"Shree Hanuman Chalisa"', '"Dark Horse"', '"Perfect"', '"Let Her Go"', '"Faded"', '"Girls Like You"', '"Lean On"'] 30

In [25]:
artist=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[2]')

In [26]:
for i in artist:
    Artist.append(i.text)
print(Artist,len(Artist))

["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', "LooLoo Kids - Nursery Rhymes and Children's Songs", 'Cocomelon - Nursery Rhymes', 'Ed Sheeran', 'Wiz Khalifa', 'Cocomelon - Nursery Rhymes', 'ChuChu TV Nursery Rhymes & Kids Songs', 'Mark Ronson', 'Miroshka TV', 'Psy', 'Get Movies', 'Ultra Records', 'Crazy Frog', 'Maroon 5', 'OneRepublic', 'Cocomelon - Nursery Rhymes', 'Katy Perry', 'Jingle Toons', 'Shakira', 'Justin Bieber', 'Ed Sheeran', 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs', 'T-Series Bhakti Sagar', 'Katy Perry', 'Ed Sheeran', 'Passenger', 'Alan Walker', 'Maroon 5', 'Major Lazer Official'] 30

In [28]:
upload_date=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[3]')

In [31]:
for i in upload_date:
    Upload_date.append(i.text)
print(Upload_date,len(Upload_date))

['14.09', '8.38', '6.87', '6.62', '6.20', '6.17', '5.88', '5.70', '5.15', '5.07', '5.05', '4.58', '4.55', '4.34', '4.00', '3.97', '3.96', '3.96', '3.91', '3.85', '3.77', '3.73', '3.73', '3.69', '3.67', '3.67', '3.61', '3.59', '3.56', '3.55'] 30

In [32]:
view=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[4]')

In [33]:
for i in view:
    Views.append(i.text)
print(Views,len(Views))

['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'January 30, 2017', 'April 6, 2015', 'May 24, 2018', 'March 6, 2014', 'November 19, 2014', 'February 27, 2018', 'July 15, 2012', 'January 31, 2012', 'April 5, 2018', 'June 16, 2009', 'January 14, 2015', 'May 31, 2013', 'June 25, 2018', 'September 5, 2013', 'June 14, 2018', 'June 4, 2010', 'October 22, 2015', 'October 7, 2014', 'January 26, 2018', 'May 10, 2011', 'February 20, 2014', 'November 9, 2017', 'July 25, 2012', 'December 3, 2015', 'May 31, 2018', 'March 22, 2015'] 30

In [34]:
df=pd.DataFrame({'Name':Name,'Artist':Artist,'Upload_date':Upload_date,'Views':Views})
df

,Name,Artist,Upload_date,Views
0,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,14.09,"June 17, 2016"
1,"""Despacito""",Luis Fonsi,8.38,"January 12, 2017"
2,"""Johny Johny Yes Papa""",LooLoo Kids - Nursery Rhymes and Children's Songs,6.87,"October 8, 2016"
3,"""Bath Song""",Cocomelon - Nursery Rhymes,6.62,"May 2, 2018"
4,"""Shape of You""",Ed Sheeran,6.20,"January 30, 2017"
5,"""See You Again""",Wiz Khalifa,6.17,"April 6, 2015"
6,"""Wheels on the Bus""",Cocomelon - Nursery Rhymes,5.88,"May 24, 2018"
7,"""Phonics Song with Two Words""",ChuChu TV Nursery Rhymes & Kids Songs,5.70,"March 6, 2014"
8,"""Uptown Funk""",Mark Ronson,5.15,"November 19, 2014"
9,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,5.07,"February 27, 2018"
10,"""Gangnam Style""",Psy,5.05,"July 15, 2012"
11,"""Masha and the Bear – Recipe for Disaster""",Get Movies,4.58,"January 31, 2012"
12,"""Dame Tu Cosita""",Ultra Records,4.55,"April 5, 2018"
13,"""Axel F""",Crazy Frog,4.34,"June 16, 2009"
14,"""Sugar""",Maroon 5,4.00,"January 14, 2015"
15,"""Counting Stars""",OneRepublic,3.97,"May 31, 2013"
16,"""Baa Baa Black Sheep""",Cocomelon - Nursery Rhymes,3.96,"June 25, 2018"
17,"""Roar""",Katy Perry,3.96,"September 5, 2013"
18,"""Lakdi Ki Kathi""",Jingle Toons,3.91,"June 14, 2018"
19,"""Waka Waka (This Time for Africa)""",Shakira,3.85,"June 4, 2010"
20,"""Sorry""",Justin Bieber,3.77,"October 22, 2015"
21,"""Thinking Out Loud""",Ed Sheeran,3.73,"October 7, 2014"
22,"""Humpty the train on a fruits ride""",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.73,"January 26, 2018"
23,"""Shree Hanuman Chalisa""",T-Series Bhakti Sagar,3.69,"May 10, 2011"
24,"""Dark Horse""",Katy Perry,3.67,"February 20, 2014"
25,"""Perfect""",Ed Sheeran,3.67,"November 9, 2017"
26,"""Let Her Go""",Passenger,3.61,"July 25, 2012"
27,"""Faded""",Alan Walker,3.59,"December 3, 2015"
28,"""Girls Like You""",Maroon 5,3.56,"May 31, 2018"
29,"""Lean On""",Major Lazer Official,3.55,"March 22, 2015"

In [35]:
#Question-2

In [36]:
driver=webdriver.Chrome()
driver.get('https://www.bcci.tv/')

In [37]:
fixtures_click=driver.find_element(By.XPATH,'/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')
fixtures_click.click()

In [60]:
series=[]
place=[]
date=[]
time=[]

In [61]:
Series=driver.find_elements(By.XPATH,'//div[@class="match-info"]/h5')
for i in Series:
    series.append(i.text)
print(series,len(series))

['ENGLAND TOUR OF INDIA 2023-24', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024'] 6

In [62]:
Place=driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
for i in Place:
    place.append(i.text)
print(place,len(place))

['Himachal Pradesh Cricket Association Stadium,', 'Harare Sports Club,', 'Harare Sports Club,', 'Harare Sports Club,', 'Harare Sports Club,', 'Harare Sports Club,'] 6

In [63]:
Date= driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in  Date:
    date.append(i.text)
print(date,len(date))

['7 MARCH, 2024', '6 JULY, 2024', '7 JULY, 2024', '10 JULY, 2024', '13 JULY, 2024', '14 JULY, 2024'] 6

In [64]:
Time=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in Time:
    time.append(i.text)
print(time,len(time))

['9:30 AM IST', '8:00 PM IST', '8:00 PM IST', '8:00 PM IST', '8:00 PM IST', '8:00 PM IST'] 6

In [65]:
df= pd.DataFrame({'Series':series,'Place':place,'Date':date,'Time':time})
df

,Series,Place,Date,Time
0,ENGLAND TOUR OF INDIA 2023-24,"Himachal Pradesh Cricket Association Stadium,","7 MARCH, 2024",9:30 AM IST
1,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club,","6 JULY, 2024",8:00 PM IST
2,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club,","7 JULY, 2024",8:00 PM IST
3,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club,","10 JULY, 2024",8:00 PM IST
4,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club,","13 JULY, 2024",8:00 PM IST
5,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club,","14 JULY, 2024",8:00 PM IST

In [66]:
#Question-3

In [2]:
driver=webdriver.Chrome()
driver.get('http://statisticstimes.com/')

In [3]:
economy=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button').click()

In [4]:
a=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]').get_attribute('href')

In [5]:
driver=webdriver.Chrome()
driver.get(a)

In [6]:
Rank=[]
State=[]
GSDP_18_19=[]
GSDP_19_20=[]
Share_18_19=[]
GDP=[]

In [10]:
state_gdp=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').get_attribute('href')

In [11]:
driver=webdriver.Chrome()
driver.get(state_gdp)

In [24]:
Rank=[]
for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[1]')[:33]:
    Rank.append(i.text)
print(Rank,len(Rank))

['1', '5', '11', '23', '25', '26', '29', '30', '31', '32', '33', '27', '28', '24', '22', '21', '20', '19', '18', '17', '16', '15', '14', '13', '12', '10', '9', '8', '7', '6', '4', '3', '2'] 33

In [25]:
State=[]
for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[2]')[:33]:
    State.append(i.text)
print(State,len(State))

['Maharashtra', 'Gujarat', 'Kerala', 'Goa', 'Chandigarh', 'Puducherry', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Meghalaya', 'Sikkim', 'Tripura', 'Himachal Pradesh', 'Jammu & Kashmir-UT', 'Uttarakhand', 'Jharkhand', 'Chhattisgarh', 'Assam', 'Punjab', 'Bihar', 'Odisha', 'Haryana', 'Delhi', 'Telangana', 'Andhra Pradesh', 'Madhya Pradesh', 'Rajasthan', 'West Bengal', 'Karnataka', 'Uttar Pradesh', 'Tamil Nadu'] 33

In [26]:
GSDP_18_19=[]
for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[4]')[:33]:
    GSDP_18_19.append(i.text)
print(GSDP_18_19,len(GSDP_18_19))

['3,108,022', '1,937,066', '932,470', '82,604', '45,635', '44,238', '36,594', '35,124', '31,913', '27,824', '10,371', '38,785', '37,557', '62,550', '176,269', '199,917', '272,159', '358,863', '406,416', '412,612', '614,227', '650,302', '670,881', '870,665', '904,642', '1,128,907', '1,133,837', '1,136,137', '1,218,193', '1,363,926', '1,962,725', '1,974,532', '2,071,286'] 33

In [27]:
GSDP_19_20=[]
for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[3]')[:33]:
    GSDP_19_20.append(i.text)
print(GSDP_19_20,len(GSDP_19_20))

['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '42,697', '42,756', '72,636', '195,405', '227,927', '302,621', '393,722', '457,608', '493,167', '673,107', '751,396', '774,869', '994,154', '1,043,759', '1,313,391', '1,317,728', '1,322,821', '1,413,620', '1,554,992', '2,241,368', '2,257,575', '2,364,514'] 33

In [28]:
GDP=[]
for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[6]')[:33]:
    GDP.append(i.text)
print(GDP,len(GDP))

['417.163', '259.996', '125.157', '11.087', '6.125', '5.938', '4.912', '4.714', '4.283', '3.735', '1.392', '5.206', '5.041', '8.396', '23.659', '26.833', '36.530', '48.167', '54.550', '55.381', '82.442', '87.284', '90.047', '116.862', '121.422', '151.523', '152.185', '152.494', '163.507', '183.068', '263.440', '265.024', '278.011'] 33

In [29]:
Share_18_19=[]
for i in driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[5]')[:33]:
    Share_18_19.append(i.text)
print(Share_18_19,len(Share_18_19))

['13.24%', '8.25%', '3.97%', '0.35%', '0.19%', '0.19%', '0.16%', '0.15%', '0.14%', '0.12%', '0.04%', '0.17%', '0.16%', '0.27%', '0.75%', '0.85%', '1.16%', '1.53%', '1.73%', '1.76%', '2.62%', '2.77%', '2.86%', '3.71%', '3.85%', '4.81%', '4.83%', '4.84%', '5.19%', '5.81%', '8.36%', '8.41%', '8.82%'] 33

In [30]:
df=pd.DataFrame({'Rank':Rank,'State':State,'GSDP_18_19':GSDP_18_19,'GSDP_19_20':GSDP_19_20,'Share_18_19':Share_18_19,'GDP':GDP})

In [33]:
df=df.sort_values(by='Rank')

In [37]:
df.reset_index(drop=True,inplace=True)

In [47]:
df

   Rank                      State GSDP_18_19 GSDP_19_20 Share_18_19      GDP
0     1                Maharashtra  3,108,022          -      13.24%  417.163
1    10                  Telangana  1,128,907  1,313,391       4.81%  151.523
2    11                     Kerala    932,470          -       3.97%  125.157
3    12                      Delhi    904,642  1,043,759       3.85%  121.422
4    13                    Haryana    870,665    994,154       3.71%  116.862
5    14                     Odisha    670,881    774,869       2.86%   90.047
6    15                      Bihar    650,302    751,396       2.77%   87.284
7    16                     Punjab    614,227    673,107       2.62%   82.442
8    17                      Assam    412,612    493,167       1.76%   55.381
9    18               Chhattisgarh    406,416    457,608       1.73%   54.550
10   19                  Jharkhand    358,863    393,722       1.53%   48.167
11    2                 Tamil Nadu  2,071,286  2,364,514       8.82%  278.011
12   20                Uttarakhand    272,159    302,621       1.16%   36.530
13   21         Jammu & Kashmir-UT    199,917    227,927       0.85%   26.833
14   22           Himachal Pradesh    176,269    195,405       0.75%   23.659
15   23                        Goa     82,604          -       0.35%   11.087
16   24                    Tripura     62,550     72,636       0.27%    8.396
17   25                 Chandigarh     45,635          -       0.19%    6.125
18   26                 Puducherry     44,238          -       0.19%    5.938
19   27                  Meghalaya     38,785     42,697       0.17%    5.206
20   28                     Sikkim     37,557     42,756       0.16%    5.041
21   29                    Manipur     36,594          -       0.16%    4.912
22    3              Uttar Pradesh  1,974,532  2,257,575       8.41%  265.024
23   30          Arunachal Pradesh     35,124          -       0.15%    4.714
24   31                   Nagaland     31,913          -       0.14%    4.283
25   32                    Mizoram     27,824          -       0.12%    3.735
26   33  Andaman & Nicobar Islands     10,371          -       0.04%    1.392
27    4                  Karnataka  1,962,725  2,241,368       8.36%  263.440
28    5                    Gujarat  1,937,066          -       8.25%  259.996
29    6                West Bengal  1,363,926  1,554,992       5.81%  183.068
30    7                  Rajasthan  1,218,193  1,413,620       5.19%  163.507
31    8             Madhya Pradesh  1,136,137  1,322,821       4.84%  152.494
32    9             Andhra Pradesh  1,133,837  1,317,728       4.83%  152.185

In [48]:
#Question-4

In [107]:
driver=webdriver.Chrome()
driver.get('https://github.com/')

In [108]:
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]

In [109]:
open_sourse_button=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button').click()

In [110]:
trending=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a').get_attribute('href')

In [111]:
driver=webdriver.Chrome()
driver.get(trending)

In [112]:
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]
Url=[]

In [63]:
for i in driver.find_elements(By.XPATH,'//a[@class="Link"]'):
    Repository_title.append(i.text)
print(Repository_title,len(Repository_title))

['WongKinYiu / yolov9', 'public-apis / public-apis', 'Azure / PyRIT', 'vvbbnn00 / WARP-Clash-API', 'tigerbeetle / tigerbeetle', 'FuelLabs / fuel-core', 'FuelLabs / sway', 'MHSanaei / 3x-ui', 'google / gemma.cpp', 'Eladlev / AutoPrompt', 'mouredev / Hello-Python', 'ossu / computer-science', 'FuelLabs / fuels-ts', 'FuelLabs / fuels-rs', 'toeverything / AFFiNE', 'MDK8888 / GPTFast', 'KillianLucas / open-interpreter', 'zksync / credo', 'electric-sql / pglite', 'massgravel / Microsoft-Activation-Scripts', 'ollama / ollama', 'angular / components', 'ashishps1 / awesome-system-design-resources', '1c7 / chinese-independent-developer', 'laurent22 / joplin'] 25

In [113]:
for i in driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]/a'):
    Url.append(i.get_attribute('href'))
print(Url,len(Url))

['https://github.com/WongKinYiu/yolov9', 'https://github.com/public-apis/public-apis', 'https://github.com/Azure/PyRIT', 'https://github.com/vvbbnn00/WARP-Clash-API', 'https://github.com/tigerbeetle/tigerbeetle', 'https://github.com/FuelLabs/fuel-core', 'https://github.com/FuelLabs/sway', 'https://github.com/MHSanaei/3x-ui', 'https://github.com/google/gemma.cpp', 'https://github.com/Eladlev/AutoPrompt', 'https://github.com/mouredev/Hello-Python', 'https://github.com/ossu/computer-science', 'https://github.com/FuelLabs/fuels-ts', 'https://github.com/FuelLabs/fuels-rs', 'https://github.com/toeverything/AFFiNE', 'https://github.com/MDK8888/GPTFast', 'https://github.com/KillianLucas/open-interpreter', 'https://github.com/zksync/credo', 'https://github.com/electric-sql/pglite', 'https://github.com/massgravel/Microsoft-Activation-Scripts', 'https://github.com/ollama/ollama', 'https://github.com/angular/components', 'https://github.com/ashishps1/awesome-system-design-resources', 'https://github.com/1c7/chinese-independent-developer', 'https://github.com/laurent22/joplin'] 25

In [115]:
for i in Url:
    driver=webdriver.Chrome()
    driver.get(i)
    try:
        repository=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[1]/div/div/p')
        Repository_description.append(repository.text)
    except:
        Repository_description.append('-')
    try:
        language=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[6]/div/ul').text.split('\n')
        Language_used.append(language.text)
    except:
        Language_used.append('-')
    try:
        contributors=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[3]/div/h2/a/span')
        Contributors_count.append(contributors.text)
    except:
        Contributors_count.append('-')
    try:
        title=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/div/div[1]/div[1]/div/strong/a')
        Repository_title.append(title.text)
    except:
        Repository_title.append('-')

In [116]:
df=pd.DataFrame({'Repository_description':Repository_description,'Language_used':Language_used,'Contributors_count':Contributors_count,'Repository_titl':Repository_title,'URL':Url})

In [117]:
df

,Repository_description,Language_used,Contributors_count,Repository_titl,URL
0,Implementation of paper - YOLOv9: Learning Wha...,-,,yolov9,https://github.com/WongKinYiu/yolov9
1,A collective list of free APIs,-,"1,262",public-apis,https://github.com/public-apis/public-apis
2,The Python Risk Identification Tool for genera...,-,,PyRIT,https://github.com/Azure/PyRIT
3,该项目可以让你通过订阅的方式使用Cloudflare WARP+，自动获取流量。This p...,-,5,WARP-Clash-API,https://github.com/vvbbnn00/WARP-Clash-API
4,The distributed financial transactions databas...,-,1,tigerbeetle,https://github.com/tigerbeetle/tigerbeetle
5,Rust full node implementation of the Fuel v2 p...,-,9,fuel-core,https://github.com/FuelLabs/fuel-core
6,🌴 Empowering everyone to build reliable and ef...,-,2,sway,https://github.com/FuelLabs/sway
7,Xray panel supporting multi-protocol multi-use...,-,1,3x-ui,https://github.com/MHSanaei/3x-ui
8,"lightweight, standalone C++ inference engine f...",-,,gemma.cpp,https://github.com/google/gemma.cpp
9,A framework for prompt tuning using Intent-bas...,-,,AutoPrompt,https://github.com/Eladlev/AutoPrompt
10,Curso para aprender el lenguaje de programació...,-,-,Hello-Python,https://github.com/mouredev/Hello-Python
11,🎓 Path to a free self-taught education in Comp...,-,,computer-science,https://github.com/ossu/computer-science
12,Fuel Network Typescript SDK,-,-,fuels-ts,https://github.com/FuelLabs/fuels-ts
13,Fuel Network Rust SDK,-,-,fuels-rs,https://github.com/FuelLabs/fuels-rs
14,There can be more than Notion and Miro. AFFiNE...,-,-,AFFiNE,https://github.com/toeverything/AFFiNE
15,Accelerate your Hugging Face Transformers 6-7x...,-,,GPTFast,https://github.com/MDK8888/GPTFast
16,A natural language interface for computers,-,235,open-interpreter,https://github.com/KillianLucas/open-interpreter
17,-,-,,credo,https://github.com/zksync/credo
18,Lightweight Postgres packaged as WASM into a T...,-,,pglite,https://github.com/electric-sql/pglite
19,A Windows and Office activator using HWID / Oh...,-,-,Microsoft-Activation-Scripts,https://github.com/massgravel/Microsoft-Activa...
20,"Get up and running with Llama 2, Mistral, Gemm...",-,-,ollama,https://github.com/ollama/ollama
21,Component infrastructure and Material Design c...,-,,components,https://github.com/angular/components
22,This repository contains System Design resourc...,-,,awesome-system-design-resources,https://github.com/ashishps1/awesome-system-de...
23,👩🏿‍💻👨🏾‍💻👩🏼‍💻👨🏽‍💻👩🏻‍💻中国独立开发者项目列表 -- 分享大家都在做什么,-,134,chinese-independent-developer,https://github.com/1c7/chinese-independent-dev...
24,Joplin - the secure note taking and to-do app ...,-,-,joplin,https://github.com/laurent22/joplin

In [97]:
#Question-5

In [10]:
driver=webdriver.Chrome()
driver.get('https:/www.billboard.com/')

In [3]:
song_name=[]
artist_name=[]
last_week_rank=[]
peak_rank=[]
weeks_on_board=[]

In [12]:
chart_click=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a').click()

In [13]:
song_chart_click=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a').click()

In [14]:
for i in driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/h3'):
    song_name.append(i.text)
print(song_name,len(song_name))

["Texas Hold 'Em", 'Lovin On Me', 'Lose Control', 'Carnival', 'Beautiful Things', 'Snooze', 'Cruel Summer', 'Greedy', 'I Remember Everything', 'Agora Hills', 'Yes, And?', 'Stick Season', 'Fast Car', 'Water', 'Last Night', 'Redrum', "Thinkin' Bout Me", "Is It Over Now? (Taylor's Version) [From The Vault]", 'Pretty Little Poison', 'Flowers', 'Paint The Town Red', 'Houdini', 'Made For Me', 'Never Lose Me', 'La Diabla', 'Where The Wild Things Are', 'Training Season', 'The Painter', 'Feather', 'What Was I Made For?', 'Rich Baby Daddy', 'Whatever She Wants', 'Truck Bed', 'Selfish', 'Everybody', 'Vampire', 'Wild Ones', 'On My Mama', 'Praise Jah In The Moonlight', 'Save Me', 'Exes', 'Breathe', 'Dance The Night', 'Need A Favor', 'Surround Sound', 'World On Fire', 'Yeah!', 'Burn It Down', 'Good Good', 'La Victima', 'End Of Beginning', 'Get In With Me', 'Burn', 'Man Made A Bar', '16 Carriages', 'First Person Shooter', 'Fuk Sumn', 'One Of The Girls', 'Back To Me', 'One Call', 'Contigo', '23', 'Murder On The Dancefloor', 'You Broke My Heart', 'Think U The Shit (Fart)', 'FTCU', 'FE!N', 'Hiss', 'I Can Feel It', 'Bandit', 'Spin You Around (1/24)', 'Soak City', 'Forever', "Mamaw's House", 'Act II: Date @ 8', 'Igual Que Un Angel', 'Nee-nah', 'Wildflowers And Wild Horses', 'Bellakeo', 'Harley Quinn', 'Standing Next To You', 'Bittersweet', 'IDGAF', 'Home', 'Vultures', 'Yeah Glo!', 'Coal', 'Mmhmm', 'Psycho CEO', 'Perro Negro', 'Sensational', 'Oklahoma Smokeshow', 'Tu Name', 'Do It', 'Worth It', 'Talking', 'Monaco', 'Where It Ends', 'Wondering Why', 'Northern Attitude'] 100

In [15]:
for i in driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/span'):
    artist_name.append(i.text)
print(artist_name,len(artist_name))

['Beyonce', 'Jack Harlow', 'Teddy Swims', '¥$: Kanye West & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', 'Benson Boone', 'SZA', 'Taylor Swift', 'Tate McRae', 'Zach Bryan Featuring Kacey Musgraves', 'Doja Cat', 'Ariana Grande', 'Noah Kahan', 'Luke Combs', 'Tyla', 'Morgan Wallen', '21 Savage', 'Morgan Wallen', 'Taylor Swift', 'Warren Zeiders', 'Miley Cyrus', 'Doja Cat', 'Dua Lipa', 'Muni Long', 'Flo Milli', 'Xavi', 'Luke Combs', 'Dua Lipa', 'Cody Johnson', 'Sabrina Carpenter', 'Billie Eilish', 'Drake Featuring Sexyy Red & SZA', 'Bryson Tiller', 'HARDY', 'Justin Timberlake', 'Nicki Minaj Featuring Lil Uzi Vert', 'Olivia Rodrigo', 'Jessie Murph & Jelly Roll', 'Victoria Monet', 'YG Marley', 'Jelly Roll With Lainey Wilson', 'Tate McRae', 'Yeat', 'Dua Lipa', 'Jelly Roll', 'JID Featuring 21 Savage & Baby Tate', 'Nate Smith', 'Usher Featuring Lil Jon & Ludacris', 'Parker McCollum', 'Usher, Summer Walker & 21 Savage', 'Xavi', 'Djo', 'BossMan Dlow', '¥$: Kanye West & Ty Dolla $ign', 'Morgan Wallen Featuring Eric Church', 'Beyonce', 'Drake Featuring J. Cole', '¥$: Kanye West & Ty Dolla $ign', 'The Weeknd, Jennie & Lily Rose Depp', '¥$: Kanye West & Ty Dolla $ign', 'Rich Amiri', 'Karol G & Tiesto', 'Chayce Beckham', 'Sophie Ellis-Bextor', 'Drake', 'Ice Spice', 'Nicki Minaj', 'Travis Scott Featuring Playboi Carti', 'Megan Thee Stallion', 'Kane Brown', 'Don Toliver', 'Morgan Wallen', '310babii', 'Noah Kahan', 'Thomas Rhett Featuring Morgan Wallen', '4Batz', 'Kali Uchis & Peso Pluma', '21 Savage, Travis Scott & Metro Boomin', 'Lainey Wilson', 'Peso Pluma & Anitta', 'Fuerza Regida & Marshmello', 'Jung Kook', 'Gunna', 'Drake Featuring Yeat', 'Good Neighbours', '¥$: Kanye West & Ty Dolla $ign Featuring Lil Durk & Bump J', 'GloRilla', 'Dylan Gossett', 'BigXthaPlug', 'Yeat', 'Bad Bunny & Feid', 'Chris Brown Featuring Davido & Lojay', 'Zach Bryan', 'Fuerza Regida', '¥$: Kanye West & Ty Dolla $ign', 'Offset & Don Toliver', '¥$: Kanye West & Ty Dolla $ign Featuring North West', 'Bad Bunny', 'Bailey Zimmerman', 'The Red Clay Strays', 'Noah Kahan With Hozier'] 100

In [18]:
for i in driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[4]'):
    last_week_rank.append(i.text)
for i in driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[5]'):
    peak_rank.append(i.text)
for i in driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[6]'):
    weeks_on_board.append(i.text)
print(last_week_rank,len(last_week_rank),peak_rank,len(peak_rank),weeks_on_board,len(weeks_on_board))

['2', '1', '5', '3', '4', '7', '6', '9', '8', '12', '31', '10', '11', '13', '14', '15', '16', '18', '24', '17', '19', '25', '32', '21', '22', '29', '-', '35', '42', '27', '41', '-', '51', '37', '40', '43', '45', '44', '63', '47', '49', '-', '46', '50', '54', '56', '20', '60', '36', '58', '-', '59', '33', '66', '38', '57', '23', '72', '26', '68', '-', '77', '73', '74', '62', '71', '76', '48', '82', '78', '70', '84', '28', '83', '81', '69', '80', '-', '87', '85', '61', '-', '88', '-', '34', '89', '95', '96', '-', '99', '-', '-', '-', '52', '-', '30', '97', '-', '-', '75'] 100 ['1', '1', '2', '3', '3', '2', '1', '3', '1', '7', '1', '10', '2', '7', '1', '5', '7', '1', '19', '1', '1', '11', '23', '18', '20', '26', '27', '28', '29', '14', '11', '32', '33', '19', '24', '1', '35', '33', '39', '19', '34', '42', '6', '13', '40', '21', '1', '48', '25', '46', '51', '52', '33', '15', '38', '1', '23', '57', '26', '60', '61', '62', '51', '11', '37', '15', '5', '1', '59', '38', '24', '61', '28', '55', '59', '22', '10', '78', '53', '40', '5', '82', '2', '77', '34', '86', '86', '65', '89', '20', '91', '72', '93', '52', '92', '30', '5', '32', '71', '37'] 100 ['2', '15', '28', '2', '5', '62', '42', '23', '26', '22', '6', '21', '48', '21', '56', '6', '51', '17', '24', '53', '29', '15', '6', '10', '10', '14', '1', '20', '12', '31', '20', '1', '36', '4', '11', '31', '20', '23', '4', '33', '14', '1', '34', '45', '15', '17', '47', '18', '28', '10', '1', '3', '2', '22', '2', '20', '2', '9', '2', '4', '1', '8', '8', '14', '4', '11', '17', '4', '8', '3', '4', '10', '2', '8', '7', '6', '6', '4', '10', '16', '16', '1', '20', '3', '2', '2', '7', '9', '1', '16', '3', '17', '1', '2', '5', '2', '19', '8', '8', '12'] 100

In [19]:
df=pd.DataFrame({'song_name':song_name,'artist_name':artist_name,'last_week_rank':last_week_rank,'peak_rank':peak_rank,'weeks_on_board':weeks_on_board})

In [20]:
df

,song_name,artist_name,last_week_rank,peak_rank,weeks_on_board
0,Texas Hold 'Em,Beyonce,2,1,2
1,Lovin On Me,Jack Harlow,1,1,15
2,Lose Control,Teddy Swims,5,2,28
3,Carnival,¥$: Kanye West & Ty Dolla $ign Featuring Rich ...,3,3,2
4,Beautiful Things,Benson Boone,4,3,5
...,...,...,...,...,...
95,Talking,¥$: Kanye West & Ty Dolla $ign Featuring North...,30,30,2
96,Monaco,Bad Bunny,97,5,19
97,Where It Ends,Bailey Zimmerman,-,32,8
98,Wondering Why,The Red Clay Strays,-,71,8
99,Northern Attitude,Noah Kahan With Hozier,75,37,12

In [21]:
driver.close()

In [22]:
#Question-6

In [23]:
driver=webdriver.Chrome()
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [28]:
Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]

In [29]:
for i in driver.find_elements(By.XPATH,'//td[@class="left"][2]'):
    Book_name.append(i.text)
for i in driver.find_elements(By.XPATH,'//td[@class="left"][3]'):
    Author_name.append(i.text)
for i in driver.find_elements(By.XPATH,'//td[@class="left"][4]'):
    Volumes_sold.append(i.text)
for i in driver.find_elements(By.XPATH,'//td[@class="left"][5]'):
    Publisher.append(i.text)
for i in driver.find_elements(By.XPATH,'//td[@class="last left"]'):
    Genre.append(i.text)

In [30]:
df=pd.DataFrame({'Book_name':Book_name,'Author_name':Author_name,'Volumes_sold':Volumes_sold,'Publisher':Publisher,'Genre':Genre})
df

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [31]:
driver.close()

In [32]:
#Question-7

In [58]:
driver=webdriver.Chrome()
driver.get('https://www.imdb.com/list/ls512407256/')

In [57]:
Name=[]
Year_span=[]
Genre=[]
Run_time=[]
Ratings=[]
Votes=[]

In [59]:
for i in driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a'):
    Name.append(i.text)
for i in driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]'):
    Year_span.append(i.text)
for i in driver.find_elements(By.CLASS_NAME,"genre"):
    Genre.append(i.text)
for i in driver.find_elements(By.CLASS_NAME,"runtime"):
    Run_time.append(i.text)
for i in driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]/span[2]'):
    Ratings.append(i.text)
for i in driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"][3]/span[2]'):
    Votes.append(i.text)

In [62]:
df=pd.DataFrame({'Name':Name,'Year_span':Year_span,'Genre':Genre,'Run_time':Run_time,'Ratings':Ratings,'Votes':Votes})

In [63]:
df

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",55 min,9.2,"2,262,002"
1,Stranger Things,(2016–2025),"Drama, Fantasy, Horror",51 min,8.7,"1,320,102"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,071,973"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"313,431"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"273,343"
...,...,...,...,...,...,...
95,True Detective,(2014– ),"Crime, Drama, Mystery",55 min,8.9,"645,066"
96,Teen Wolf,(2011–2017),"Action, Drama, Fantasy",41 min,7.7,"162,030"
97,The OA,(2016–2019),"Drama, Fantasy, Mystery",60 min,7.8,"114,843"
98,The Simpsons,(1989– ),"Animation, Comedy",22 min,8.7,"433,031"
99,Desperate Housewives,(2004–2012),"Comedy, Drama, Mystery",45 min,7.6,"138,660"

In [37]:
#Question-8

In [84]:
driver=webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/')

In [85]:
Dataset_name=[]
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attribute=[]

In [86]:
view_dataset=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]').click()

In [67]:
#Since there are 664 dataset and there are 25 dataset per page so we will have to iterate 27 times

In [87]:
for i in range(26):
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/h2/a'):
        Dataset_name.append(i.text)
    for i in driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[1]/span'):
        Data_type.append(i.text)
    for i in driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/p'):
        Task.append(i.text)
    for i in driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[2]/span'):
        Attribute_type.append(i.text)
    for i in driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[3]/span'):
        No_of_instances.append(i.text)
    for i in driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div[4]/span[1]'):
        No_of_attribute.append(i.text)
    next_button=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')
    next_button.click()
driver.close()

In [88]:
df=pd.DataFrame({'Dataset_name':Dataset_name,'Data_type':Data_type,'Task':Task,'Attribute_type':Attribute_type,'No_of_instances':No_of_instances,'No_of_attributes':No_of_attribute})

In [89]:
df

,Dataset_name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes
0,Iris,Classification,"A small classic dataset from Fisher, 1936. One...",Tabular,150 Instances,4 Features
1,Dry Bean Dataset,Classification,"Images of 13,611 grains of 7 different registe...",Multivariate,13.61K Instances,16 Features
2,Heart Disease,Classification,"4 databases: Cleveland, Hungary, Switzerland, ...",Multivariate,303 Instances,13 Features
3,Rice (Cammeo and Osmancik),Classification,A total of 3810 rice grain's images were taken...,Multivariate,3.81K Instances,7 Features
4,Adult,Classification,Predict whether income exceeds $50K/yr based o...,Multivariate,48.84K Instances,14 Features
...,...,...,...,...,...,...
645,Newspaper and magazine images segmentation dat...,Classification,Dataset is well suited for segmentation tasks....,null,101 Instances,
646,GitHub MUSAE,Classification,A social network of GitHub users with user-lev...,Multivariate,37.7K Instances,
647,Roman Urdu Sentiment Analysis Dataset (RUSAD),Classification,The dataset was gathered to carry out research...,Text,11K Instances,
648,Victorian Era Authorship Attribution,Classification,To create the largest authorship attribution d...,Text,93.6K Instances,
649,: Simulated Data set of Iraqi tourism places,"Classification, Clustering",Simulated Data set of Iraqi tourism places wit...,Multivariate,232 Instances,4.81K Features